services:
  app:
    image: ghcr.io/possesion/zvuchi-vocal:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - /root/web/zvuchi-vocal/.env/
      # - /Users/gennadykazantsev/Documents/coding/vocal-school/.env
    volumes:
      - zvuchi_data:/app/data

volumes:
  zvuchi_data:
