services:
  app:
    image: ghcr.io/possesion/zvuchi-vocal:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - /root/web/zvuchi-vocal/.env
    volumes:
      - /root/web/zvuchi-vocal/data:/app/standalone/data
    dns:
      - 8.8.8.8
      - 8.8.4.4

